
name: CI_Execute_Test

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2


      - name: Run tests
        run : |
          chmod +x ./project/tests.sh
          ./project/tests.sh
